# Generated by Django 4.2.5 on 2024-02-11 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tunduk", "0002_alter_company_options_company_infocom_and_more"),
        ("accounts", "0002_alter_customuser_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tunduk.company",
                verbose_name="КС пользователя",
            ),
        ),
    ]
