version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: postgres_container
    volumes:
      - ./compose/db/db:/var/lib/postgresql/data
      - ./compose/db/maintenance:/usr/local/bin/maintenance
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - django-network

  app:
    build:
      context: .
      dockerfile: compose/back/Dockerfile
    volumes:
      - .:/app
      - ./static:/app/static
      - ./media:/app/media
    expose:
      - 8000
    env_file:
      - ./venv/.env.dev
    image: fccu-backend
    container_name: fccu-backend
    command: poetry run gunicorn core.wsgi:application --bind 0.0.0.0:8000  --workers=4
    networks:
      - django-network
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: compose/nginx/Dockerfile
    ports:
      - 80:8000
    volumes:
      - ./compose/nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
    networks:
      - django-network
    depends_on:
      - app


volumes:
  static_volume:
  media_volume:

networks:
  django-network:
    name: django-network