# Generated by Django 4.2.5 on 2023-10-20 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TundukRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('request_type', models.CharField(choices=[('Инфоком', 'Инфоком'), ('Унаа', 'Унаа'), ('Мин. Юст', 'Мин. Юст'), ('Кадастр', 'Кадастр')], help_text='В какой сервис отправлен запрос', max_length=20, verbose_name='Тип запроса')),
                ('data', models.JSONField(default=dict, verbose_name='Запрошенные данные')),
                ('file', models.FileField(blank=True, null=True, upload_to='tunduk/%m.%y', verbose_name='Фото / Документ запрашиваемого')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время изменения')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Автор запроса')),
            ],
            options={
                'verbose_name': 'Журнал запросов',
                'verbose_name_plural': 'Журнал запросов',
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Дата/время изменения')),
                ('model', models.CharField(max_length=255, null=True, verbose_name='Таблица')),
                ('record_id', models.IntegerField(null=True, verbose_name='ID записи')),
                ('action_on_model', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление')], max_length=50, null=True, verbose_name='Действие')),
                ('data', models.JSONField(default=dict, verbose_name='Изменяемые данные модели')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Автор изменения')),
            ],
            options={
                'verbose_name': 'Журнал изменений',
                'verbose_name_plural': 'Журнал изменений',
                'ordering': ('-changed',),
            },
        ),
    ]
