# Generated by Django 4.2.5 on 2023-11-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tundukrequestlog',
            name='request_type',
            field=models.CharField(choices=[('Инфоком', 'Инфоком'), ('Унаа', 'Унаа'), ('Мин. Юст', 'Мин. Юст'), ('Кадастр', 'Кадастр'), ('Мин. Сель. Хоз', 'Мин. Сель. Хоз')], help_text='В какой сервис отправлен запрос', max_length=20, verbose_name='Тип запроса'),
        ),
    ]
