# Generated by Django 4.2.5 on 2024-02-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=300, verbose_name="Название компании"),
                ),
                (
                    "client_id",
                    models.CharField(
                        help_text="ID клиента в тундук, пример: ak_jol_2000",
                        max_length=150,
                        verbose_name="ID клиента",
                    ),
                ),
                (
                    "infocom_secret_key",
                    models.CharField(
                        help_text="Секретный ключ выдаваемый от Инфоком",
                        max_length=150,
                        verbose_name="Секретный ключ клиента",
                    ),
                ),
                (
                    "ip_addr",
                    models.CharField(
                        help_text="IP Адрес сервера тундук",
                        max_length=30,
                        verbose_name="IP Адрес",
                    ),
                ),
                (
                    "member_code",
                    models.CharField(
                        help_text="Код участника тундук, пример: 60000165",
                        max_length=30,
                        verbose_name="Код участника тундук",
                    ),
                ),
                (
                    "subsystem_code",
                    models.CharField(
                        help_text="Название участника передаваемый от тундук, пример: akzhol_subsystem",
                        max_length=100,
                        verbose_name="Название участника в тундук",
                    ),
                ),
            ],
        ),
    ]
