# Generated by Django 4.2.5 on 2024-02-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tunduk", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "Компания", "verbose_name_plural": "Компании"},
        ),
        migrations.AddField(
            model_name="company",
            name="infocom",
            field=models.BooleanField(default=True, verbose_name="Инфоком"),
        ),
        migrations.AddField(
            model_name="company",
            name="kadastr",
            field=models.BooleanField(default=False, verbose_name="Кадастр"),
        ),
        migrations.AddField(
            model_name="company",
            name="minjyst",
            field=models.BooleanField(default=False, verbose_name="Мин. Юст"),
        ),
        migrations.AddField(
            model_name="company",
            name="minselxoz",
            field=models.BooleanField(default=False, verbose_name="Мин. Сель. Хоз"),
        ),
        migrations.AddField(
            model_name="company",
            name="unaa",
            field=models.BooleanField(default=False, verbose_name="Унаа"),
        ),
    ]
